using System.Collections.Generic;

namespace BugFablesLib;

public static partial class BfVanillaNames
{
  public static IReadOnlyList<string> Discoveries => new[]
  {
    "Snakemouth Den",
    "Snakemouth Depths",
    "Explorer's Message",
    "The Roaches' Village?",
    "Inn Foremothers",
    "The Settler Statue",
    "The Ants",
    "The Bees",
    "The Termites",
    "The Wasps",
    "Queen Elizant I",
    "The Anthill Palace",
    "Aphids and Cochineals",
    "The Golden Festival",
    "The Goddess' Statue",
    "Honored Employee",
    "Sand Castle Mural",
    "Snakemouth's Lab",
    "Healing Sophie",
    "Seedling Haven",
    "Underground Tavern",
    "The Ant Mines",
    "Chomper Cavern",
    "The Power Plant",
    "Termite Statue",
    "The Bee Kingdom",
    "Balcony Telescope",
    "B.O.S.S.",
    "Defiant Root",
    "Relic Museum",
    "The Lost Sands",
    "Tardigrade Idol",
    "Bandit Hideout",
    "Stream Mountain",
    "Far Grasslands",
    "Fishing Village",
    "Wizard's Tower",
    "Wild Swamplands",
    "Wasp Kingdom",
    "Forsaken Lands",
    "Ancient City",
    "Termite Kingdom",
    "Termacade",
    "Termite Colosseum",
    "Metal Island",
    "Spy Cards",
    "Peacock Island",
    "Rubber Prison",
    "Giant's Lair",
    "Sailor's Statue"
  };
}
