using System.Collections.Generic;

namespace BugFablesLib.Names;

internal static partial class Names
{
  internal static IList<string> s_items = new List<string>
  {
    "Crunchy Leaf",
    "Honey Drop",
    "Spicy Berry",
    "Burly Berry",
    "Super Pepper",
    "Iron Seed",
    "RESERVED",
    "RESERVED",
    "Mistake",
    "Leaf Omelet",
    "Honey'd Leaf",
    "Magic Seed",
    "Clear Water",
    "Mushroom",
    "Cooked Shroom",
    "Mushroom Salad",
    "Leaf Salad",
    "Aphid Egg",
    "Fried Egg",
    "Hearty Breakfast",
    "Glazed Honey",
    "Sweet Shroom",
    "Sweet Danger",
    "Hard Seed",
    "Dotted Ball",
    "Bug Ranger Plushie",
    "Danger Shroom",
    "Explorer Permit",
    "Cooked Danger",
    "Coal Crystal",
    "Spicy Bomb",
    "Poison Bomb",
    "Queen's Dinner",
    "Mushroom Skewer",
    "Roasted Berries",
    "Abomihoney",
    "Clear Bomb",
    "Ant Compass",
    "Chomper Seed",
    "Berry Juice",
    "Numbnail Dart",
    "Map of Bugaria",
    "Magic Ice",
    "Shock Berry",
    "Frost Bomb",
    "Numb Bomb",
    "Sleep Bomb",
    "Shaved Ice",
    "Aphid Dew",
    "Honey Ice Cream",
    "Sweet Dew",
    "Ice Cream",
    "Lore Book",
    "Cold Salad",
    "Flower Key",
    "Sun Offering",
    "Moon Offering",
    "Mothiva Doll",
    "Wooden Crank",
    "Big Crank Top Half",
    "Big Crank",
    "Big Crank Bottom Half",
    "Abombination",
    "Spy Data",
    "Danger Spud",
    "Baked Yam",
    "Spicy Fries",
    "Burly Chips",
    "Bag of Flour",
    "Yam Bread",
    "Spicy Candy",
    "Burly Candy",
    "Dry Bread",
    "Nutty Cake",
    "Poison Cake",
    "Shock Candy",
    "Plain Tea",
    "Tangy Berry",
    "Tangy Jam",
    "Tangy Juice",
    "Spicy Tea",
    "Burly Tea",
    "Frost Pie",
    "Heart Berry",
    "Bond Berry",
    "Tangy Pie",
    "Crisbee Donut",
    "Tangy Carpaccio",
    "Poison Dart",
    "Bed Bug",
    "Succulent Berry",
    "Succulent Platter",
    "Desert Key",
    "Overdue Book",
    "Pretty Ribbon",
    "Factory Pass",
    "Agaric Shroom",
    "Shell Ointment",
    "Crimson Ore",
    "Bee Hat",
    "Blank Card",
    "1-Suit Card",
    "2-Suit Card",
    "3-Suit Card",
    "Full Suit Card",
    "Heaven Key",
    "Earth Key",
    "Longleg Summoner",
    "Stolen Silk",
    "Mysterious Piece",
    "Game Tokens",
    "Rusty Key",
    "Orange Horn",
    "Sand Castle Key",
    "Ancient Key",
    "Big Ancient Key",
    "Peculiar Gem",
    "Top Hat",
    "Crystal Fruit",
    "Wasp Key",
    "Jayde's Stew",
    "Dark Cherries",
    "Cherry Pie",
    "Miracle Shake",
    "Berry Smoothie",
    "Squash",
    "Squash Candy",
    "Sophie Petal",
    "Succulent Cookies",
    "Sweet Pudding",
    "Mega-Rush™",
    "HP Potion",
    "ATK Potion",
    "DEF Potion",
    "TP Potion",
    "Super HP Potion",
    "Super TP Potion",
    "MP Potion",
    "Shady Note",
    "Blackest Paint",
    "Red Paint",
    "Root Cloth",
    "Ant Doll",
    "Eastern Doll",
    "Mushroom Gummies",
    "Wrapped Lunch",
    "Crystal Crown",
    "Drowsy Cake",
    "Leaf Croissant",
    "Package",
    "Crystal Feather",
    "Crystal Fang",
    "Cherry Bombs",
    "Squash Puree",
    "Mite Burger",
    "Aphid Shake",
    "Mystery Berry",
    "Small Gear",
    "Medium Gear",
    "Big Gear",
    "Lab Card",
    "Prison Key",
    "Hustle Berry",
    "History Book",
    "History Book",
    "History Book",
    "History Book",
    "Leaf Umbrella",
    "Venom Ribbon",
    "Shocking Ribbon",
    "Drowsy Ribbon",
    "Big Mistake",
    "Burly Bomb",
    "Berry Jam",
    "Bad Book",
    "Mechanical Claw",
    "Platinum Card",
    "Hot Drink",
    "Hustle Candy",
    "Squash Tart",
    "Plumpling Pie",
    "Danger Dish",
    "Honey Pancakes",
    "Flame Rock",
    "Card Trophy",
    "Team Ribbon"
  };
}
