using System.Collections.Generic;

namespace BugFablesLib;

public static partial class BfVanillaNames
{
  public static IReadOnlyList<string> Musics => new[]
  {
    "Outskirts",
    "Let's fight, team!",
    "Snakemouth Den",
    "They Call Him Spuder",
    "The Everlasting Sapling",
    "Where Adventurers Gather",
    "Getting Stronger!",
    "Fine Arts",
    "It's Getting Scary!",
    "Let's Fry with Fry!",
    "The One Left Behind",
    "DOT UNUSED (Beetle)",
    "Bug Fables",
    "Blessed Golden Lands",
    "Dodgy Business",
    "In The Court of The Ant Queen",
    "The Sacred Hills",
    "Mothiva! SUPERSTAR!",
    "Harvest Festival",
    "Frenzied Sunflower Dance",
    "Venus, Goddess of Bountiful Harvests",
    "Defiant Root",
    "The Bandits' Hideout",
    "Team, this one's stronger!",
    "Lost Sands",
    "Oh no! WASPS!",
    "wind ambient",
    "water ambient",
    "Work that Honey",
    "Kut it Up!",
    "Make it Crisbee!",
    "Bee Kingdom, Miles Above",
    "Mecha Bee Destroyer Blastlord",
    "Store that Honey",
    "The Ones Who...",
    "Bugaria's Latest Sensation!",
    "Bianca, Queen of All Bees",
    "Drums of War",
    "DOT MACHINE HUM AMBIENT",
    "The Watcher",
    "Lost Castle of Ancient Worship",
    "Swamp Where Dreams Drown",
    "Forsaken Lands",
    "Team, it's getting serious!",
    "Caves",
    "Elizant II's Promise",
    "Cruel Beast, Devourer of Journeys",
    "Lands Untamed",
    "Snug as a Bug in a Sub",
    "Termite Capitol",
    "breathing ambient",
    "DineMite Beats",
    "Wasp Kingdom",
    "Rubber Prison",
    "Ant Kingdom, Under Attack...!",
    "Summer Holiday at the Metal Island™",
    "Reckless For Glory",
    "Centipede Attacks",
    "Lab Over Snakemouth",
    "Flower Journey",
    "The Other One",
    "Battle Against Ultimax, Who Has A Tank",
    "????",
    "The Giant's Lair",
    "DOT UNUSED (Giant2)",
    "DOT UNUSED (Giant3)",
    "The Usurper, Grasping for Power",
    "Trascended, Overpowering, Everlasting",
    "Mite Knight",
    "Team... We've done it!",
    "The Sailors' Pier",
    "A Long Journey's End",
    "The Usurper",
    "Bustling Ant Kingdom!"
  };
}
