using System.Collections.Generic;

namespace BugFablesLib;

public static partial class BfVanillaNames
{
  public static IReadOnlyList<string> Recipes => new[]
  {
    "Mistake",
    "Leaf Salad",
    "Glazed Honey",
    "Abomihoney",
    "Cooked Shroom",
    "Cooked Danger",
    "Sweet Shroom",
    "Sweet Danger",
    "Fried Egg",
    "Leaf Omelet",
    "Honey'd Leaf",
    "Roasted Berries",
    "Succulent Platter",
    "Succulent Cookies",
    "Berry Juice",
    "Mushroom Skewer",
    "Hearty Breakfast",
    "Mushroom Salad",
    "Sweet Dew",
    "Baked Yam",
    "Spicy Fries",
    "Burly Chips",
    "Danger Dish",
    "Shaved Ice",
    "Cold Salad",
    "Ice Cream",
    "Honey Ice Cream",
    "Dry Bread",
    "Nutty Cake",
    "Poison Cake",
    "Frost Pie",
    "Yam Bread",
    "Shock Candy",
    "Mushroom Gummies",
    "Sweet Pudding",
    "Leaf Croissant",
    "Honey Pancakes",
    "Drowsy Cake",
    "Hustle Candy",
    "Spicy Candy",
    "Burly Candy",
    "Berry Jam",
    "Hot Drink",
    "Plain Tea",
    "Spicy Tea",
    "Burly Tea",
    "Aphid Shake",
    "Squash Puree",
    "Squash Candy",
    "Squash Tart",
    "Plumpling Pie",
    "Tangy Jam",
    "Tangy Juice",
    "Tangy Pie",
    "Spicy Bomb",
    "Burly Bomb",
    "Poison Bomb",
    "Sleep Bomb",
    "Numb Bomb",
    "Frost Bomb",
    "Clear Bomb",
    "Abombination",
    "Cherry Bombs",
    "Cherry Pie",
    "Berry Smoothie",
    "Miracle Shake",
    "Tangy Carpaccio",
    "Crisbee Doughnut",
    "Queen's Dinner",
    "Big Mistake"
  };
}
