using System.Collections.Generic;

namespace BugFablesLib;

internal static partial class Names
{
  internal static IList<string> s_enemies = new List<string>
  {
    "Zombiant",
    "Jellyshroom",
    "Spider",
    "Zasp",
    "Cactiling",
    "Psicorp",
    "Thief",
    "Bandit",
    "Inichas",
    "Seedling",
    "Flying Seedling",
    "Maki",
    "Web",
    "Spider",
    "Numbnail",
    "Mothiva",
    "Acornling",
    "Weevil",
    "Mr. Tester",
    "Venus' Bud",
    "Chomper",
    "Acolyte Aria",
    "Vine",
    "Kabbu",
    "Venus' Guardian",
    "Wasp Trooper",
    "Wasp Bomber",
    "Wasp Driller",
    "Wasp Scout",
    "Midge",
    "Underling",
    "Monsieur Scarlet",
    "Golden Seedling",
    "Arrow Worm",
    "Carmina",
    "Seedling King",
    "Broodmother",
    "Plumpling",
    "Flowerling",
    "Burglar",
    "Astotheles",
    "Mother Chomper",
    "Ahoneynation",
    "Bee-Boop",
    "Security Turret",
    "Denmuki",
    "Heavy Drone B-33",
    "Mender",
    "Abomihoney",
    "Dune Scorpion",
    "Tidal Wyrm",
    "Kali",
    "Zombee",
    "Zombeetle",
    "The Watcher",
    "Peacock Spider",
    "Bloatshroom",
    "Krawler",
    "Haunted Cloth",
    "Sand Wall",
    "Ice Wall",
    "Warden",
    "Wasp King",
    "Jumping Spider",
    "Mimic Spider",
    "Leafbug Ninja",
    "Leafbug Archer",
    "Leafbug Clubber",
    "Madesphy",
    "The Beast",
    "Chomper Brute",
    "Mantidfly",
    "General Ultimax",
    "Wild Chomper",
    "Cross",
    "Poi",
    "Primal Weevil",
    "False Monarch",
    "Mothfly",
    "Mothfly Cluster",
    "Ironnail",
    "Belostoss",
    "Ruffian",
    "Water Strider",
    "Diving Spider",
    "Cenn",
    "Pisci",
    "Dead Lander α",
    "Dead Lander β",
    "Dead Lander γ",
    "Wasp King",
    "The Everlasting King",
    "Maki",
    "Kina",
    "Yin",
    "ULTIMAX Tank",
    "Zommoth",
    "Riz",
    "Devourer",
    "Tail",
    "Rock Wall",
    "Ancient Key",
    "Ancient Key",
    "Ancient Tablet",
    "Flytrap",
    "FireKrawler",
    "FireWarden",
    "FireCape",
    "IceKrawler",
    "IceWarden",
    "TANGYBUG",
    "Stratos",
    "Delilah"
  };
}
