using System.Collections.Generic;

namespace BugFablesLib;

internal static partial class Names
{
  internal static IList<string> s_medals = new List<string>
  {
    "HP Plus",
    "TP Plus",
    "Detector",
    "Last Attack",
    "Last Stand",
    "Quick Flea",
    "Poison Attacker",
    "Poison Resistance",
    "Berserker",
    "Poison Defender",
    "Empower",
    "Hard Mode",
    "Sleep Resistance",
    "Mighty Pebble",
    "Spiky Bod",
    "Break",
    "Break+",
    "Spy Specs",
    "Bug Me Not!",
    "Super Block+",
    "Favorite One",
    "Numb Resistance",
    "Poison Needles",
    "Strong Start",
    "Weak Stomach",
    "TP Saver",
    "Reverse Toxin",
    "Eternal Venom",
    "A.D.B.P Enhancer",
    "Mightier Pebble",
    "Hard Hits",
    "Empower+",
    "Life Stealer",
    "Freeze Resistance",
    "Shock Trooper",
    "Front Support",
    "Back Support",
    "Enfeeble",
    "Enfeeble+",
    "Fortify",
    "Fortify+",
    "Sleepy Needles",
    "EXP Booster",
    "Status Booster",
    "Poison Touch",
    "Status Relay",
    "Frostbite",
    "Heavy Sleeper",
    "Secure Pouch",
    "Power Exchange",
    "Defense Exchange",
    "Tardigrade Shield",
    "Charge Up",
    "Charge Up+",
    "Leaf Cloak",
    "Random Start",
    "Meditation",
    "Electric Needles",
    "Block Heal",
    "Extra Freeze",
    "Heavy Throw",
    "Reflection",
    "Prayer",
    "Antlion Jaws",
    "HP Core",
    "TP Core",
    "Resist All",
    "Deep Taunt",
    "Miracle Matter",
    "Victory Buzz",
    "Triumph Buzz",
    "Crazy Prepared",
    "Life Cast",
    "Hard Charge",
    "Heal Plus",
    "Status Mirror",
    "Luckier Day",
    "First Plating",
    "Seedling Affinity",
    "Berry Finder"
  };
}
